### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by Stephonomon** [nicebread/shinyApps#1]
The buttons next to Show all on the main page do not work. Also, what did you to create the gallery?

![image](https://user-images.githubusercontent.com/9829881/62906486-e342bd00-bd3c-11e9-8e52-02cd7ecf1b50.png)

**Comment by nicebread** [comment]
Thanks for the note - I now fixed a bug and the buttons do work (they filter the apps according to that keyword).
This gallery was created with https://isotope.metafizzy.co/

**Comment by Stephonomon** [comment]
Thanks. I’m new to web dev and looked at the documentation for Isotope. Do you mind sharing the build for that page on github so that I can use it to make my own? I work well when I can reverse engineer.
